Scripts/distribution/urls.py
from django.urls import path

from . import views

#应用的名称
app_name='distribution'

urlpatterns=[
    #主页
    path('',views.index,name='index'),
    #显示所有已经注册的医院
    path('hospitals/',views.hospitals,name='hospitals'),
    #显示某所医院所需医疗物资
    path('hospitals/<int:hospital_id>/',views.hospital,name='hospital'),
    #用于添加新的医院信息
    path('new_hospital',views.new_hospital,name='new_hospital'),
    #用于添加新的所需物资
    path('add_need/<int:hospital_id>/',views.add_need,name='add_need'),
    #修改所需物资
    path('edit_need/<int:need_id>/',views.edit_need,name='edit_need'),
]

Scripts/hospitalusers/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView

from . import views

app_name='hospitalusers'

urlpatterns=[
    #登录界面
    path('login/',LoginView.as_view(template_name='hospitalusers/login.html'),name='login'),
    #注销
    path('logout/',views.logout_view,name='logout'),
    #注册
    path('register/',views.register,name='register'),

]

Scripts/msds/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hospitalusers/',include(('hospitalusers.urls','hospitalusers'),namespace='hospitalusers')),
    path('',include(('distribution.urls','distribution'),namespace='distribution')),
]

Scripts/distribution/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Hospital(models.Model):
    """"医院方"""
    name=models.CharField(max_length=200)
    address=models.CharField(max_length=200)
    last_login=models.DateField(auto_now=True)
    owner=models.ForeignKey(User,on_delete=models.CASCADE)
    def __str__(self):
        return self.name[:20]+'...'


class M_material(models.Model):
    """医疗物资的情况"""

    #定义模板常量
    mask='mask'
    protective_suit='protective_suit'
    goggles='goggles'
    bloodbag='bloodbag'

    #医疗物资名称的元组
    MATERIAL_CHOICE=((mask,'mask'),(protective_suit,'protective_suit'),
                     (goggles,'goggles'),(bloodbag,'bloodbag'),)

    hospital=models.ForeignKey(Hospital,on_delete=models.CASCADE)
    name=models.CharField(max_length=30,choices=MATERIAL_CHOICE)
    need_num=models.IntegerField()
    urgency=models.IntegerField()

    def __str__(self):
        return self.name + str(self.need_num)

Scripts/hospitalusers/models.py
from django.db import models

# Create your models here.

Scripts/distribution/forms.py
from django import forms

from .models import Hospital,M_material

class HospitalForm(forms.ModelForm):
    class Meta:
        model = Hospital
        fields = ['name','address']
        labels = {'name':'name','address':'address'}


class M_materialForm(forms.ModelForm):
    class Meta:
        model = M_material
        fields = ['name','need_num','urgency']
        labels = {'name':'supplies_name'}

Scripts/distribution/views.py
from django.shortcuts import render,redirect
from django.urls import reverse
from django.http import Http404
from django.contrib.auth.decorators import login_required

from .models import Hospital,M_material
from .forms import HospitalForm,M_materialForm

def index(request):
    """分配网站的首页"""
    return render(request,'distribution/index.html')

@login_required
def hospitals(request):
    """显示所有已经注册的医院"""
    hospitals=Hospital.objects.order_by('last_login')
    context={'hospitals':hospitals}
    return render(request,'distribution/hospitals.html',context)

@login_required
def hospital(request,hospital_id):
    """显示某一医院所需的医疗物资"""
    hospital=Hospital.objects.get(id=hospital_id)
    needs=hospital.m_material_set.order_by('-urgency')
    context={'hospital':hospital,'needs':needs}
    return render(request,'distribution/hospital.html',context)

@login_required
def new_hospital(request):
    """添加新的医院信息"""
    if request.method !='POST':
        form = HospitalForm()
    else:
        form = HospitalForm(request.POST)
        if form.is_valid():
            new_hospital = form.save(commit=False)
            new_hospital.owner =request.user
            new_hospital.save()
            return redirect(reverse('distribution:hospitals'))

    context ={'form':form}
    return render(request,'distribution/new_hospital.html',context)

@login_required
def add_need(request,hospital_id):
    """添加新的物资信息"""
    hospital = Hospital.objects.get(id=hospital_id)
    if hospital.owner != request.user:
        raise Http404
    if request.method != 'POST':
        form = M_materialForm()
    else:
        form = M_materialForm(data=request.POST)
        if form.is_valid():
            new_need = form.save(commit=False)
            new_need.hospital = hospital
            new_need.save()
            return redirect(reverse('distribution:hospital',args=[hospital_id]))

    context={'form':form,'hospital':hospital}
    return render(request,'distribution/add_need.html',context)

@login_required
def edit_need(request,need_id):
    need = M_material.objects.get(id=need_id)
    hospital = need.hospital
    if hospital.owner != request.user:
        raise Http404
    if request.method != 'POST':
        form = M_materialForm(instance=need)
    else:
        form = M_materialForm(instance=need,data=request.POST)
        if form.is_valid():
            now_need = form.save(commit=True)
            now_need.hospital = hospital
            now_need.save()
            return redirect(reverse('distribution:hospital',args=[hospital.id]))

    context={'form':form,'need':need,'hospital':hospital}
    return render(request,'distribution/edit_need.html',context)

Scripts/hospitalusers/views.py
from django.shortcuts import render,redirect
from django.urls import reverse
from django.contrib.auth import logout,login,authenticate


from django.contrib.auth.forms import UserCreationForm

def logout_view(request):
    """注销用户"""
    logout(request)
    return redirect(reverse('distribution:index'))


def register(request):
    """注册新用户"""
    if request.method !='POST':
        #显示空的注册表单
        form=UserCreationForm()
    else:
        #处理填写好的表单
        form=UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user=form.save()
            #让用户自动登录，再重定向到主页
            authenticated_user=authenticate(username=new_user.username,password=request.POST['password1'])
            login(request,authenticated_user)
            return redirect(reverse('distribution:index'))

    context={'form':form}
    return render(request,'hospitalusers/register.html',context)

Scripts/distribution/templates/distribution/add_need.html
{% extends 'distribution/base.html' %}
{% load bootstrap3 %}

{% block header %}
<h2><a href="{% url 'distribution:hospital' hospital.id %}">{{ hospital.name }}</a></h2>
{% endblock header %}

{% block content %}
<form action="{% url 'distribution:add_need' hospital.id %}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button name="submit">add need</button>
    {% endbuttons %}
</form>

{% endblock content %}

Scripts/distribution/templates/distribution/base.html
<!DOCTYPE html>
{% load bootstrap3 %}

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MSDS</title>

    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>

<!-- Staic navbar -->
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed"
        data-toggle="collapse" data-target="#navbar"
        aria-expanded="false" aria-controls="navbar">
            </button>
 <a class="navbar-brand" href="{% url 'distribution:index' %}">MSDS</a>
</div>

<div id="navbar" class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
     <li><a href="{% url 'distribution:hospitals' %}">Hospital</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
        <li><a>Hello,{{user.username}}.</a></li>
        <li><a href="{% url 'hospitalusers:logout' %}">log out</a></li>
        {% else %}
        <li><a href="{% url 'hospitalusers:register' %}">register</a></li>
        <li><a href="{% url 'hospitalusers:login' %}">log in</a></li>
        {% endif %}
    </ul>
</div><!-- /.nav-collapse-->

</div>
</nav>

<div class="container">

<div class="page-header">
    {% block header %}{% endblock header %}
</div>

<div>
    {% block content %}{% endblock content %}
</div>

</div><!--/container -->

</body>

</html>

Scripts/distribution/templates/distribution/edit_need.html
{% extends "distribution/base.html" %}
{% load bootstrap3 %}

{% block header %}
<h2><a href="{% url 'distribution:hospital' hospital.id %}">{{ hospital.name }}</a></h2>
<h3>Edit need:</h3>
{% endblock header %}

{% block content %}

<form action="{% url 'distribution:edit_need' need.id %}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button name="submit">add need</button>
    {% endbuttons %}
</form>
{% endblock content %}

Scripts/distribution/templates/distribution/hospital.html
{% extends "distribution/base.html" %}

{% block header %}
<h2>{{hospital.name}}</h2>
<h3>{{hospital.address}}</h3>
{% endblock header %}

{% block content %}
<h3>
    <a href="{% url 'distribution:add_need' hospital.id %}">add need</a>
</h3>

    {% for need in needs %}
    <div class="panel panel-default">
        <div class="panel-heading">
        <h4>{{need.name}}
            <small><a href="{% url 'distribution:edit_need' need.id %}">edit need</a>
            </small>
        </h4>
        </div>
        <div class="panel-body">
        <h5>
           need_num:  {{need.need_num}}  urgency: {{need.urgency}}%
        </h5>
        </div>
    </div><!--panel -->
{% empty %}
        This hospital's medical supplies are enough.
    {% endfor %}

{% endblock content %}

Scripts/distribution/templates/distribution/hospitals.html
{% extends "distribution/base.html" %}

{% block header %}
<h2>Hospitals</h2>
<h3><a href="{% url 'distribution:new_hospital' %}">Add new hospital</a></h3>
{% endblock header %}

{% block content %}
<ul>
    {% for hospital in hospitals %}
    <li>
        <h3>
            <a href="{% url 'distribution:hospital' hospital.id %}">{{hospital.name}}</a>
        </h3>
        <h4>{{hospital.address}}</h4>
    </li>
    {% empty %}
    <li>No hospitals have been added yet.</li>
    {% endfor%}
</ul>

{% endblock content %}

Scripts/distribution/templates/distribution/index.html
{% extends "distribution/base.html" %}

{% block header %}
<div class="jumbotron">
    <h1>Welcome to MSDS.</h1>
    </div>
{% endblock header %}

{% block content %}
<h2>This web will help you to distribute medical supplies to those hospitals which need them.</h2>
{% endblock content %}

Scripts/distribution/templates/distribution/new_hospital.html
{% extends "distribution/base.html" %}
{% load bootstrap3 %}

{% block header %}
<h2>Add a new hospital:</h2>
{% endblock header %}

{% block content %}
<form action="{% url 'distribution:new_hospital' %}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button name="submit" class="btn btn-primary">add hospital</button>
    {% endbuttons %}
</form>
{% endblock content %}

Scripts/hospitalusers/templates/hospitalusers/login.html
{% extends "distribution/base.html" %}
{% load bootstrap3 %}

{% block header %}
<h2>Log in your account.</h2>
{% endblock header %}

{% block content %}

<form action="{% url 'hospitalusers:login' %}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
    <button name="submit" class="btn btn-primary">log in</button>
    {% endbuttons %}

    <input type="hidden" name="next" value="{% url 'distribution:index' %}"/>

</form>

{% endblock content %}

Scripts/hospitalusers/templates/hospitalusers/register.html
{% extends "distribution/base.html" %}
{% load bootstrap3 %}

{% block header %}
<h2>Register now</h2>
{% endblock header %}

{% block content %}
<form action="{% url 'hospitalusers:register' %}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button name="submit" class="btn btn-primary">register</button>
    {% endbuttons %}
    <input type="hidden" name="next" value="{% url 'distribution:index' %}"/>
</form>

{% endblock content %}